stages:
  - package

package:
  stage: package
  image:
    name: mcr.microsoft.com/dotnet/core/sdk:2.2
  before_script:
    - echo "<?xml version='1.0' encoding='utf-8'?><configuration><packageSources><add key='ADOFeed' value='$ADO_NUGET_URL' /></packageSources><packageSourceCredentials><ADOFeed><add key='Username' value='$ADO_USER' /><add key='ClearTextPassword' value='$ADO_ACCESS_TOKEN' /></ADOFeed></packageSourceCredentials></configuration>" > NuGet.Config
  script:
    - dotnet restore Scriptor\Scriptor.csproj
    - cd Scriptor
    - dotnet build Scriptor.csproj -c Release
    - dotnet pack -c Release --no-build --no-restore -o ./app
    - dotnet nuget push ./app/*.nupkg -s $ADO_NUGET_URL -k AzureDevOps
  only:
    - master
  when: manual
