# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:


- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: |
      Scriptor\Scriptor.csproj
      Scriptor.AspExtensions\Scriptor.AspExtensions.csproj
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      Scriptor\Scriptor.csproj
      Scriptor.AspExtensions\Scriptor.AspExtensions.csproj
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: |
      Scriptor\Scriptor.csproj
      Scriptor.AspExtensions\Scriptor.AspExtensions.csproj
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'



- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'